# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AudioFile-Find
version:      0.01
version_from: lib/AudioFile/Find.pm
installdirs:  site
requires:
    AudioFile::Info:               1.09
    AudioFile::Info::Audio::WMA:   0.1
    AudioFile::Info::MP3::Info:    1.04
    AudioFile::Info::Ogg::Vorbis::Header::PurePerl: 1.05
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
